POST http://localhost:3001/api/patients
content-type: application/json

{
"name": "2017-05-11",
"dateOfBirth": "sunnsy",
"ssn": "123123",
"gender": "ok",
"occupation": "good stuf"
}

###
POST http://localhost:3001/api/patients
content-type: application/json

{
"name": "2017-05-11",
"dateOfBirth": "asd",
"ssn": "123123",
"gender": "ok",
"occupation": "good stuf"
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
content-type: application/json

{
  "id": "d811e46d-70b3-4d90-b090-4535c7cf8fb1",
  "date": "2015-01-02",
  "type": "Hospital",
  "specialist": "MD House",
  "diagnosisCodes": [
    "S62.5"
  ],
  "description": "Healing time appr. 2 weeks. patient doesn't remember how he got the injury.",
  "discharge": {
    "date": "2015-01-16",
    "criteria": "Thumb has healed."
  }
}
